doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
#         dql:
#             string_functions:
#                 JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
#                 JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch
#         dql:
#             string_functions:
#                 JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Sqlite\JsonExtract
#                 JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Sqlite\JsonSearch
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Modules\User\Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/User/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Modules\User\Domain'
                alias: App\Modules\User\Domain
            App\Modules\Greeting\Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/Greeting/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Modules\Greeting\Domain'
                alias: App\Modules\Greeting\Domain

        controller_resolver:
            auto_mapping: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
            url: '%env(resolve:DATABASE_URL)%'
        orm:
            auto_generate_proxy_classes: true
            auto_mapping: false

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
