mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: [ '*' ]
                subscribe: [ 'https://symfony.test/greetings', 'https://symfony.test/greeting/{id}' ]
