App\Modules\User\Application\ChangePassword\ChangePasswordRequest:
  properties:
    currentPassword:
      - NotBlank: ~
    password:
      - NotBlank: ~
    passwordConfirmation:
      - NotBlank: ~
      - EqualTo:
          propertyPath: password
          message: 'Passwords do not match.'
