App\Modules\User\Application\CreateUser\CreateUserRequest:
  properties:
    email:
      - Email:
          message: The email {{ value }} is not a valid email.
      - NotBlank: ~
    password:
      - NotBlank: ~
    passwordConfirmation:
      - NotBlank: ~
      - EqualTo:
          propertyPath: password
          message: 'Passwords do not match.'
